//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int MaterialId { get; set; }
        public string Denumire { get; set; }
        public decimal Cantitate { get; set; }
        public decimal Pret { get; set; }
        public System.DateTime DataAprovizonare { get; set; }
    
        public virtual Operatie Operatie { get; set; }
    }
}
