//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operatie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operatie()
        {
            this.Materials = new HashSet<Material>();
        }
    
        public int OperatieId { get; set; }
        public string Denumire { get; set; }
        public decimal TimpExecutie { get; set; }
    
        public virtual Mecanic Mecanic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Materials { get; set; }
    }
}
